file = open('codingal.txt', 'r')
print("reading first line...")
print(file.readline())
print("Now reading multiple lines")
file = open('codingal.txt', 'r')
print(file.readline())
print(file.readline())
print(file.readline())
file.close()